FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    tesseract-ocr \
    tesseract-ocr-eng \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt pyproject.toml ./
RUN pip install --no-cache-dir --default-timeout=1000 --retries 5 -r requirements.txt
RUN pip install --no-cache-dir -e .

COPY . .

CMD ["python", "-m", "worker.main"]
