"""
Integration Tests for Member 4 Deterministic Rules Engine.
HUMAN-ONLY ZONE: Owned by Member 4 (Sravanthi).

Validates end-to-end integration across all 5 deterministic rules:
  1. RULE-COMP-01 (Completeness)
  2. RULE-INC-01 (Salary vs Bank Credit)
  3. RULE-TAX-01 (Tax Return vs Stated Income)
  4. RULE-ID-01 (Cross-Document Identity)
  5. RULE-BANK-01 (Bank Statement Arithmetic)

Verifies that actual evaluated rule findings strictly match expected ground-truth outcomes
across all controlled anomaly scenarios generated by scripts/generate_dossiers.py:
  - clean
  - missing_payslip / missing_itr
  - salary_mismatch
  - tax_mismatch
  - identity_mismatch
  - multiple_inconsistencies
"""

from typing import Dict

from core.contracts.findings import Finding
from core.rules import evaluate_dossier_rules, findings_to_dict
from scripts.generate_dossiers import generate_dossier


def test_integration_clean_dossier(tmp_path):
    """Clean dossier: All 5 rules must independently evaluate to PASS with full provenance."""
    manifest = generate_dossier(seed=201, scenario="clean", output_dir=str(tmp_path))
    findings = evaluate_dossier_rules(dossier_manifest=manifest)

    assert len(findings) == 5
    f_map: Dict[str, Finding] = findings_to_dict(findings)

    expected = manifest["expected_rule_outcomes"]
    for rule_id, expected_verdict in expected.items():
        assert rule_id in f_map, f"Missing finding for {rule_id}"
        assert f_map[rule_id].verdict == expected_verdict, (
            f"Verdict mismatch for {rule_id}: got {f_map[rule_id].verdict}, expected {expected_verdict}"
        )
        assert f_map[rule_id].policy_version == "v1.0"
        assert len(f_map[rule_id].supporting_evidence) > 0

    assert f_map["RULE-COMP-01"].verdict == "pass"
    assert f_map["RULE-INC-01"].verdict == "pass"
    assert f_map["RULE-TAX-01"].verdict == "pass"
    assert f_map["RULE-ID-01"].verdict == "pass"
    assert f_map["RULE-BANK-01"].verdict == "pass"


def test_integration_missing_payslip_dossier(tmp_path):
    """Missing payslip dossier: RULE-COMP-01 flags; salary and tax rules return UNKNOWN."""
    manifest = generate_dossier(seed=202, scenario="missing_payslip", output_dir=str(tmp_path))
    findings = evaluate_dossier_rules(dossier_manifest=manifest)

    assert len(findings) == 5
    f_map = findings_to_dict(findings)

    expected = manifest["expected_rule_outcomes"]
    for rule_id, expected_verdict in expected.items():
        assert f_map[rule_id].verdict == expected_verdict

    assert f_map["RULE-COMP-01"].verdict == "flag"
    assert "payslip" in f_map["RULE-COMP-01"].reason
    assert f_map["RULE-INC-01"].verdict == "unknown"
    assert f_map["RULE-TAX-01"].verdict == "unknown"
    assert f_map["RULE-ID-01"].verdict == "pass"  # KYC and bank names match
    assert f_map["RULE-BANK-01"].verdict == "pass"


def test_integration_missing_itr_dossier(tmp_path):
    """Missing ITR dossier: RULE-COMP-01 flags; tax audit returns UNKNOWN; others pass."""
    manifest = generate_dossier(seed=203, scenario="missing_itr", output_dir=str(tmp_path))
    findings = evaluate_dossier_rules(dossier_manifest=manifest)

    assert len(findings) == 5
    f_map = findings_to_dict(findings)

    expected = manifest["expected_rule_outcomes"]
    for rule_id, expected_verdict in expected.items():
        assert f_map[rule_id].verdict == expected_verdict

    assert f_map["RULE-COMP-01"].verdict == "flag"
    assert "tax_acknowledgement" in f_map["RULE-COMP-01"].reason
    assert f_map["RULE-INC-01"].verdict == "pass"
    assert f_map["RULE-TAX-01"].verdict == "unknown"
    assert f_map["RULE-ID-01"].verdict == "pass"
    assert f_map["RULE-BANK-01"].verdict == "pass"


def test_integration_salary_mismatch_dossier(tmp_path):
    """Salary mismatch dossier: Only RULE-INC-01 flags; all other rules pass."""
    manifest = generate_dossier(seed=204, scenario="salary_mismatch", output_dir=str(tmp_path))
    findings = evaluate_dossier_rules(dossier_manifest=manifest)

    assert len(findings) == 5
    f_map = findings_to_dict(findings)

    expected = manifest["expected_rule_outcomes"]
    for rule_id, expected_verdict in expected.items():
        assert f_map[rule_id].verdict == expected_verdict

    assert f_map["RULE-COMP-01"].verdict == "pass"
    assert f_map["RULE-INC-01"].verdict == "flag"
    assert "Salary discrepancy detected" in f_map["RULE-INC-01"].reason
    assert f_map["RULE-TAX-01"].verdict == "pass"
    assert f_map["RULE-ID-01"].verdict == "pass"
    assert f_map["RULE-BANK-01"].verdict == "pass"


def test_integration_tax_mismatch_dossier(tmp_path):
    """Tax mismatch dossier: Only RULE-TAX-01 flags; all other rules pass."""
    manifest = generate_dossier(seed=205, scenario="tax_mismatch", output_dir=str(tmp_path))
    findings = evaluate_dossier_rules(dossier_manifest=manifest)

    assert len(findings) == 5
    f_map = findings_to_dict(findings)

    expected = manifest["expected_rule_outcomes"]
    for rule_id, expected_verdict in expected.items():
        assert f_map[rule_id].verdict == expected_verdict

    assert f_map["RULE-COMP-01"].verdict == "pass"
    assert f_map["RULE-INC-01"].verdict == "pass"
    assert f_map["RULE-TAX-01"].verdict == "flag"
    assert "Tax return discrepancy" in f_map["RULE-TAX-01"].reason
    assert f_map["RULE-ID-01"].verdict == "pass"
    assert f_map["RULE-BANK-01"].verdict == "pass"


def test_integration_identity_mismatch_dossier(tmp_path):
    """Identity mismatch dossier: Only RULE-ID-01 flags; all other rules pass."""
    manifest = generate_dossier(seed=206, scenario="identity_mismatch", output_dir=str(tmp_path))
    findings = evaluate_dossier_rules(dossier_manifest=manifest)

    assert len(findings) == 5
    f_map = findings_to_dict(findings)

    expected = manifest["expected_rule_outcomes"]
    for rule_id, expected_verdict in expected.items():
        assert f_map[rule_id].verdict == expected_verdict

    assert f_map["RULE-COMP-01"].verdict == "pass"
    assert f_map["RULE-INC-01"].verdict == "pass"
    assert f_map["RULE-TAX-01"].verdict == "pass"
    assert f_map["RULE-ID-01"].verdict == "flag"
    assert "Critical identity mismatch" in f_map["RULE-ID-01"].reason
    assert f_map["RULE-BANK-01"].verdict == "pass"


def test_integration_multiple_inconsistency_dossier(tmp_path):
    """Multiple inconsistencies dossier: Salary, tax, and identity flag; completeness and bank pass."""
    manifest = generate_dossier(seed=207, scenario="multiple_inconsistencies", output_dir=str(tmp_path))
    findings = evaluate_dossier_rules(dossier_manifest=manifest)

    assert len(findings) == 5
    f_map = findings_to_dict(findings)

    expected = manifest["expected_rule_outcomes"]
    for rule_id, expected_verdict in expected.items():
        assert f_map[rule_id].verdict == expected_verdict

    assert f_map["RULE-COMP-01"].verdict == "pass"
    assert f_map["RULE-INC-01"].verdict == "flag"
    assert f_map["RULE-TAX-01"].verdict == "flag"
    assert f_map["RULE-ID-01"].verdict == "flag"
    assert f_map["RULE-BANK-01"].verdict == "pass"


def test_integration_bank_arithmetic_mismatch_in_dossier(tmp_path):
    """Injected bank statement arithmetic mismatch triggers RULE-BANK-01 flag without altering other rules."""
    manifest = generate_dossier(seed=208, scenario="clean", output_dir=str(tmp_path))

    # Tamper closing balance by ₹5,000 to induce arithmetic discrepancy
    manifest["financial_ground_truth"]["bank_closing_balance"] += 5000.0

    findings = evaluate_dossier_rules(dossier_manifest=manifest)
    f_map = findings_to_dict(findings)

    assert f_map["RULE-BANK-01"].verdict == "flag"
    assert "Bank statement arithmetic discrepancy" in f_map["RULE-BANK-01"].reason
    assert "exceeds ₹0.05 tolerance" in f_map["RULE-BANK-01"].reason

    # Other rules remain completely unaffected
    assert f_map["RULE-COMP-01"].verdict == "pass"
    assert f_map["RULE-INC-01"].verdict == "pass"
    assert f_map["RULE-TAX-01"].verdict == "pass"
    assert f_map["RULE-ID-01"].verdict == "pass"


def test_integration_all_rules_independent_and_non_overwriting(tmp_path):
    """Verifies that all 5 findings are independent typed Finding models with unique IDs and provenance."""
    manifest = generate_dossier(seed=209, scenario="clean", output_dir=str(tmp_path))
    findings = evaluate_dossier_rules(dossier_manifest=manifest)

    assert len(findings) == 5
    rule_ids = [f.rule_id for f in findings]
    assert len(set(rule_ids)) == 5  # No duplicate rule IDs

    expected_ids = ["RULE-COMP-01", "RULE-INC-01", "RULE-TAX-01", "RULE-ID-01", "RULE-BANK-01"]
    assert rule_ids == expected_ids

    for finding in findings:
        assert isinstance(finding, Finding)
        assert finding.verdict in ("pass", "flag", "unknown")
        assert len(finding.reason) > 0
        assert finding.policy_version == "v1.0"
        assert isinstance(finding.supporting_evidence, list)
